# Generated by Django 3.1.7 on 2021-04-29 11:20

import datetime
from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210414_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateField(default=datetime.date(2021, 4, 29)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(default=datetime.date(2021, 4, 29), validators=[main.validators.validate_age]),
        ),
    ]
